# Generated by Django 4.1.5 on 2023-06-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='')),
                ('date_start', models.DateField(verbose_name='')),
                ('text', models.TextField(verbose_name='Konusu')),
                ('price', models.FloatField(verbose_name='')),
            ],
        ),
    ]
